language: ruby
bundler_args: --without xml_adapter html_adapter other_rss_parser
rvm:
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-19mode
  - ruby-head
  - jruby-head
script: bundle exec rake spec
